- name: Create LetsEncrypt folder to store TLS certificates
  ansible.builtin.file:
    path: /letsencrypt
    state: directory
    mode: 600
    owner: root

- name: Create and start Traefik container
  community.docker.docker_container:
    recreate: yes
    image: docker.io/traefik:2.6
    state: started
    hostname: traefik
    name: traefik
    restart_policy: unless-stopped
    env:
      # TRAEFIK_LOG_LEVEL: "DEBUG"
      TRAEFIK_API_DASHBOARD: "true"
      TRAEFIK_API_INSECURE: "true"

      TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: ":80"
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO: "websecure"

      TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: ":443"

      TRAEFIK_PROVIDERS_DOCKER: "true"
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: "false"

      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_TLSCHALLENGE: "true"
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL: "{{ admin_email }}"
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_STORAGE: "/letsencrypt/acme.json"
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_CASERVER: "https://acme-v02.api.letsencrypt.org/directory"
    volumes:
      - /letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "[::]:80:80"
      - "443:443"
      - "[::]:443:443"
    labels:
      traefik.enable: "true"
      traefik.http.services.traefik.loadbalancer.server.port: "8080"
      traefik.http.routers.traefik.rule: "Host(`traefik.{{ domain }}`)"
      traefik.http.routers.traefik.tls.certresolver: "letsencrypt"
