version: "3"

services:
  app:
    image: portainer/portainer-ee:latest
    container_name: "{{ service_name }}"
    restart: unless-stopped
    ports:
      - 9443:9443
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data:
    name: "{{ service_name }}"
    driver: local
    driver_opts:
      type: nfs
      o: "addr=nas.blnc.io,nolock,soft,rw,nfsvers=4,async"
      device: ":/mnt/pool1/docker-nfs-volumes/{{ service_name }}"
