all:
  vars:
    domain: blnc.io
  children:
    rpi:
      vars:
        ansible_user: lazaro
        ansible_become: yes
      hosts:
        pi4:
    servers:
      vars:
        ansible_user: root
      children:
        docker:
        rpi:
      hosts:
        nas:
    docker:
      hosts:
        docker1:
