all:
  children:
    rpi:
      vars:
        ansible_user: lazaro
        ansible_become: yes
      hosts:
        pi4:
    servers:
      vars:
        ansible_user: root
      children:
        docker:
    docker:
      hosts:
        docker1:
