version: "3"

services:
  app:
    container_name: "{{ service_name }}"
    image: itzg/minecraft-server:java17
    pull_policy: always
    restart: unless-stopped
    hostname: "{{ service_name }}"
    network_mode: bridge
    tty: true
    stdin_open: true
    ports:
      - 25565:25565 # Game Port
      - 25566:25566 # Prometheus Exporter
      - 8123:8123 # Dynmap
    environment:
      EULA: "true"
      TYPE: FABRIC
      VERSION: 1.19.3
      MAX_TICK_TIME: "-1"
      VIEW_DISTANCE: "16"
      MEMORY: 4G
      EXEC_DIRECTLY: "true"
      SEED: "-2643081233096849611"
      STOP_SERVER_ANNOUNCE_DELAY: 15
      ENABLE_ROLLING_LOGS: "true"
      TZ: Europe/Berlin
      USE_AIKAR_FLAGS: "true"
    volumes:
      - data:/data

volumes:
  data:
    name: "{{ service_name }}"
    driver: local
    driver_opts:
      type: nfs
      o: "addr=nas.home.blnc.io,nolock,soft,rw,nfsvers=4,async"
      device: ":/mnt/pool1/docker-nfs-volumes/{{ service_name }}"
