- name: Install Docker
  include_role:
    name: geerlingguy.docker

- name: Install Python Package Manager (pip)
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install Docker Python SDK
  ansible.builtin.pip:
    name: docker
    state: present
