- name: Deploy blnc.io services
  hosts: hetzner
  strategy: free

  tasks:
    - name: Apply SSH role
      include_role:
        name: ssh

    - name: Apply common role
      include_role:
        name: common

    - name: Apply Docker role
      include_role:
        name: docker
