- name: Deploy blnc.io services
  hosts: hetzner
  strategy: free

  tasks:
    - name: Create sshd configuration
      include_role:
        name: ssh

    - name: Common tasks for all servers
      include_role:
        name: common

    - name: Apply Docker role
      include_role:
        name: docker
