- name: Deploy blnc.io services
  hosts: hetzner
  strategy: free
  vars_files:
    - ./secrets.yml

  tasks:
    - name: Apply SSH role
      include_role:
        name: ssh

    - name: Apply common role
      include_role:
        name: common

    - name: Apply Docker role
      include_role:
        name: docker

    - name: Apply Traefik role
      include_role:
        name: traefik
