- name: Deploy blnc.io services
  hosts: all
  strategy: free

  tasks:
    - name: Create sshd configuration
      include_role:
        name: willshersystems.sshd
      vars:
        sshd:
          PrintMotd: no
          PrintLastLog: no
          PasswordAuthentication: no
          ChallengeResponseAuthentication: no

    - name: Set motd
      ansible.builtin.template:
        src: ./files/motd.j2
        dest: /etc/motd

    - name: Install Docker
      include_role:
        name: geerlingguy.docker

    - name: Install Python Package Manager (pip)
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install Docker Python SDK
      ansible.builtin.pip:
        name: docker
        state: present
