version: "3"

services:
  app:
    image: prom/prometheus:latest
    container_name: "{{ service_name }}"
    restart: unless-stopped
    user: root
    network_mode: bridge
    ports:
      - 9090:9090
    volumes:
      - "{{ local_docker_directory }}/{{ service_name }}/prometheus.yml:/prometheus/prometheus.yml"
      - data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - '--storage.tsdb.retention.time=3y'
    # labels:
    #   traefik.enable: "true"
    #   traefik.http.services.prometheus.loadbalancer.server.port: "9090"

    #   traefik.http.routers.prometheus.rule: "Host(`prometheus.{{ domain }}`)"
    #   traefik.http.routers.prometheus.entryPoints: websecure
    #   traefik.http.routers.prometheus.middlewares: authentik@file

volumes:
  data:
    name: "{{ service_name }}"
    driver: local
    driver_opts:
      type: nfs
      o: "addr=nas.blnc.io,nolock,soft,rw,nfsvers=4,async"
      device: ":/mnt/pool1/docker-nfs-volumes/{{ service_name }}"
